## NumPy Arrays

In [1]:
import numpy as np

In [2]:
mylist = list(range(4))

In [7]:
mylist

[0, 1, 2, 3]

In [11]:
type(mylist)

list

In [14]:
array = np.array(mylist)

In [15]:
array

array([0, 1, 2, 3])

In [16]:
my_mat = [[1, 2, 3], [4, 5,6], [7, 8, 9]]

In [17]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2,2), dtype='int')

array([[1, 1],
       [1, 1]])

In [29]:
np.linspace(1, 10, 15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [30]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
np.random.rand(2)

array([0.39280866, 0.56057046])

In [36]:
np.random.rand(2,2)

array([[0.76763692, 0.7869957 ],
       [0.91477559, 0.10020333]])

In [37]:
np.random.randn(3)

array([-0.32340219,  0.59289548,  0.77683982])

In [38]:
np.random.randn(2,3)

array([[ 2.04738278,  0.32180359,  0.43715908],
       [ 2.47832957, -0.08518678, -0.71211753]])

In [6]:
np.random.randint(1, 100, (3,3))

array([[94, 53,  8],
       [54, 51, 64],
       [54, 91, 69]])

In [7]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [9]:
arr = np.arange(1, 31)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
len(arr)

30

In [55]:
arr.reshape(5, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [11]:
age = np.random.randint(0, 101, 10)
age

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [12]:
age.max()

99

In [13]:
age.min()

2

In [14]:
age.argmax()

5

In [15]:
age.argmin()

7

In [16]:
age.dtype

dtype('int32')

In [17]:
age.shape

(10,)

In [18]:
re_age = age.reshape(2, 5)

In [19]:
re_age

array([[82, 86, 74, 74, 87],
       [99, 23,  2, 21, 52]])

In [21]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[3]

3

In [23]:
arr[1:5]

array([1, 2, 3, 4])

In [24]:
arr[:5]

array([0, 1, 2, 3, 4])

In [66]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [67]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[:2] = 55

In [27]:
arr

array([55, 55,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr = np.arange(0, 11)

In [29]:
sl_arr = arr[:5]
sl_arr

array([0, 1, 2, 3, 4])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
sl_arr[:] = 99
sl_arr

array([99, 99, 99, 99, 99])

In [32]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [33]:
arr_copy = arr.copy()

In [34]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [36]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [72]:
print(arr)
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0 0 0 0 0 0]


In [39]:
a2d = np.arange(2, 8)
a2d

array([2, 3, 4, 5, 6, 7])

In [41]:
a2d2 = np.array([[5, 10, 15],[20, 25, 30], [35, 40, 45]])

In [42]:
a2d2.shape

(3, 3)

In [43]:
a2d2[1]

array([20, 25, 30])

In [44]:
a2d2[1,1]

25

In [45]:
a2d2[1][1]

25

In [91]:
a2d2[0, 2]

15

In [92]:
a2d2[:2, 1:]

array([[10, 15],
       [25, 30]])

In [46]:
arr = np.arange(1, 11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
prediction = np.random.rand(10)

In [100]:
boolean = prediction > 0.5

In [101]:
prediction[boolean]

array([0.78517596, 0.51423444, 0.59241457, 0.60754485, 0.94888554])

In [105]:
np.random.sample(10)

array([0.68423303, 0.44015249, 0.12203823, 0.49517691, 0.03438852,
       0.9093204 , 0.25877998, 0.66252228, 0.31171108, 0.52006802])

In [106]:
dice = np.random.randint(1, 6, 20)
over_two = dice > 2
len(dice[over_two])

11

In [107]:
dice

array([2, 4, 5, 2, 2, 4, 2, 2, 4, 4, 1, 5, 5, 2, 5, 2, 1, 4, 4, 4])

In [53]:
arr = np.arange(0, 10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr -5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [57]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr / arr

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3540\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [60]:
-3 / arr[0]

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3540\2268002213.py:1: RuntimeWarning: divide by zero encountered in scalar divide
  -3 / arr[0]


-inf

In [61]:
arr = np.arange(0, 25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [62]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [63]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [64]:
np.log(arr)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3540\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])

In [65]:
arr.sum()

300

In [66]:
arr.mean()

12.0

In [67]:
arr.max()

24

In [68]:
arr.min()

0

In [69]:
arr.var()

52.0

In [70]:
arr.std()

7.211102550927978

In [72]:
arr2d = np.arange(0, 25).reshape(5, 5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
arr2d.sum()

300

In [74]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [75]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

## NumPY Exercise

In [99]:
import numpy as np

In [100]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [145]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [146]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [104]:
np.linspace(10, 50, 21)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [105]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [106]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.random.rand(1)

array([0.28484049])

In [109]:
np.random.randn(25)

array([-0.28080629,  0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ,
        0.4777541 , -0.25902864, -0.57470921, -0.42149822,  0.33982096,
       -0.00738015,  0.76729684, -1.14979258, -0.77533611,  0.77314086,
       -0.80182784,  1.38401572,  1.40520531,  1.39232575, -0.88064082,
        0.07689495, -0.49343248,  0.92316261,  1.70660495,  0.87358942])

In [116]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [111]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [125]:
mat = np.arange(1, 26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [126]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [127]:
mat[3, 4]

20

In [147]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [130]:
mat[4]

array([21, 22, 23, 24, 25])

In [139]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [140]:
mat.sum()

325

In [143]:
mat.std()

7.211102550927978

In [144]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])